name: spk_hp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^1.20.0
  carousel_slider: ^4.1.1
  dropdown_search: ^5.0.2
  firebase_auth: ^3.5.0
  get_storage: ^2.0.3
  cloud_firestore: ^3.4.0
  lottie: ^1.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

