// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG55knzo5dXb-ue_gPd36ev_V10AUyyA0',
    appId: '1:297270123186:android:4463cf23bcfc07cbe247ab',
    messagingSenderId: '297270123186',
    projectId: 'spk-hp',
    storageBucket: 'spk-hp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrzv3DDYkf0xZE2CEQzdexrPEd6V1FXXw',
    appId: '1:297270123186:ios:636d9ca29958140ae247ab',
    messagingSenderId: '297270123186',
    projectId: 'spk-hp',
    storageBucket: 'spk-hp.appspot.com',
    androidClientId: '297270123186-2d7arcjhoo55od1m9keit91qq3hfjrgf.apps.googleusercontent.com',
    iosClientId: '297270123186-itg47201omcd3ghh5u99dn64p6eq2ref.apps.googleusercontent.com',
    iosBundleId: 'com.example.spkHp',
  );
}
